trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job!
    - bash: echo $(PipelineLivelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build Second Job!
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob Job!
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)DeployJob Job!
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn: 
  - QADeploy
  - DevDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo  $(environment)DeployJob Job!
  
