trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Build First Job!
  - job: SecondJob
    steps:
    - script: echo Build Second Job!
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob Job!
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob Job!
- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo ProdDeployJob Job!
  
